---

- name: AWS Web Setup
  hosts: hostileadminweb
  user: "{{ clouduser }}"
  become: yes
  become_user: "{{ becomeuser }}"

  vars_files:
    - vars/main.yml

  tasks:
    - name: Install AWS EPEL, nginx
      command: amazon-linux-extras install "{{ item }}" -y
      with_items:
        - epel
        - nginx1
      tags:
        - update
    - name: Install/update packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - git
        - nc
        - nmap
        - '*'
      tags:
        - update
      notify: Reboot

    - name: Setup filesystem for git repo
      file:
        state: absent
        path: "{{ docroot  }}"
      tags:
        - deployweb
    - name: Clone git repo
      git:
        repo: '{{ siterepo }}'
        dest: "{{ docroot }}"
        accept_hostkey: yes
        single_branch: yes
        version: master
      tags:
        - deployweb

    - name: Restart nginx
      service:
        name: nginx
        enabled: yes
        state: restarted

  handlers:
    - name: Reboot
      reboot:
